<?php
/**
 * @package Application
 * @author Yury Ostapenko
 *
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
?>

<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Next 5')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink()
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->appendFile($this->basePath('js/handlebars.min-v4.0.11.js'))
        ->appendFile($this->basePath('js/jquery-3.2.1.min.js'))
        ->appendFile($this->basePath('js/bootstrap.min.js'))
        ->appendFile($this->basePath('js/script.js'))
    ?>
</head>
<body>
<header>
    <nav class="navbar navbar-dark bg-dark box-shadow justify-content-between navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                Yury Ostapenko - Next 5
            </a>
            <ul class="navbar-nav">
                <li class="nav-item<?php if ($this->url() == $this->url('home')): ?> active<?php endif; ?>">
                    <a class="nav-link" href="<?= $this->url('home') ?>">
                        Home
                        <?php if ($this->url() == $this->url('home')): ?>
                            <span class="sr-only">(current)</span>
                        <?php endif; ?>
                    </a>
                </li>
                <li class="nav-item<?php if ($this->url() == $this->url('next-generate')): ?> active<?php endif; ?>">
                    <a class="nav-link" href="<?= $this->url('next-generate') ?>">
                        Generate Data
                        <?php if ($this->url() == $this->url('next-generate')): ?>
                            <span class="sr-only">(current)</span>
                        <?php endif; ?>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<main>
    <div class="container">
        <?= $this->content ?>
    </div>
</main>
<?= $this->inlineScript() ?>
</body>
</html>