<div class="jumbotron">
    <div class="container">
        <h1>Next 5</h1>
        <p>
            To make it easy for the customers to place bets on upcoming races that are close to starting, this app displays the Next 5 upcoming races, sorted by time.
        </p>
        <p>
            <a class="btn btn-secondary btn-lg" href="https://github.com/yukkaeast/next5" target="_blank">Fork this demo app on GitHub &raquo;</a>
        </p>
    </div>
</div>